name: Kivo.chat Build Action

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Cache Yarn Dependencies
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Kivo.chat
        run: yarn build

      - name: Type Check (TS)
        run: yarn tsc --noEmit

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: nextjs-build
          path: .next/
